In [10]:
import pandas as pd
import numpy as np
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

In [7]:
df = pd.read_csv("iris.csv")
df

sepal.length  sepal.width  petal.length  petal.width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [8]:
(train_set, test_set) = train_test_split(df.values, train_size=0.7, random_state=10)
train_input = list(map(lambda x: x[:-1], train_set))
train_label = list(map(lambda x: x[4], train_set))

test_input = list(map(lambda x: x[:-1], test_set))
test_label = list(map(lambda x: x[4], test_set))

In [12]:
classifiers = [
    tree.DecisionTreeClassifier(),
    KNeighborsClassifier(n_neighbors=3),
    KNeighborsClassifier(n_neighbors=5),
    KNeighborsClassifier(n_neighbors=11),
    GaussianNB()
  ]

In [15]:
def calculate(classifier):
  clf = classifier.fit(train_input, train_label)
  pred = clf.predict(test_input)
  counter = 0
  for i, j in zip(test_label, list(pred)):
      if i == j:
          counter += 1
  print(counter, counter/len(pred))
  print(confusion_matrix(test_label, pred, labels=["virginica", "setosa", "versicolor"]))

In [16]:
for i in classifiers:
    calculate(i)

44 0.9777777777777777
[[13  0  1]
 [ 0 14  0]
 [ 0  0 17]]
44 0.9777777777777777
[[14  0  0]
 [ 0 14  0]
 [ 1  0 16]]
44 0.9777777777777777
[[14  0  0]
 [ 0 14  0]
 [ 1  0 16]]
45 1.0
[[14  0  0]
 [ 0 14  0]
 [ 0  0 17]]
45 1.0
[[14  0  0]
 [ 0 14  0]
 [ 0  0 17]]
